// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production" | "development";
	TOKEN_SERVICE_URL: "https://freedom-production-21ce.up.railway.app" | "http://localhost:8790";
}
